# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree

# We don't have the configure script checked in, and no test rule yet
script:
  - ./autogen.sh
  - ./configure --disable-silent-rules --prefix=
  - make clean
  - make -j5 all
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - LD_LIBRARY_PATH=~/tmp/lib ldd ~/tmp/sbin/mdnsd
  - size ~/tmp/sbin/mdnsd
  - size ~/tmp/lib/libmdnsd.so.0.0.0
  - LD_LIBRARY_PATH=~/tmp/lib ~/tmp/sbin/mdnsd -h
